# Generated by Django 4.2 on 2024-01-22 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_Module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normal_user',
            name='user_status',
            field=models.CharField(choices=[('normal', 'عادی'), ('partially_banned', 'مسدودیت ناقص'), ('fully_banned', 'مسدودیت کامل')], default='normal', max_length=20, verbose_name='وضعیت کاربر'),
        ),
        migrations.CreateModel(
            name='user_false_password_attemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attemp_date', models.DateTimeField(auto_now_add=True, verbose_name='date of attemp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='suspicious user')),
            ],
        ),
    ]
