# Generated by Django 5.1.6 on 2025-04-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_Module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normal_user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
    ]
