# Generated by Django 4.2 on 2024-02-14 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_Module', '0003_user_notifications_delete_user_messages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_notifications',
            options={'verbose_name': 'اعلان کاربر', 'verbose_name_plural': 'اعلانات کاربران'},
        ),
        migrations.AlterModelTable(
            name='user_notifications',
            table='user notifications',
        ),
    ]
