# Generated by Django 4.2 on 2024-02-21 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_Module', '0004_alter_user_notifications_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='عنوان تیکت')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد تیکت')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
            ],
        ),
        migrations.CreateModel(
            name='ticket_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=400, verbose_name=' متن پیام')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد پیام')),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_Module.ticket_message', verbose_name='پیام والد')),
                ('parent_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_Module.user_ticket', verbose_name='تیکت والد')),
            ],
        ),
    ]
