# Generated by Django 4.2 on 2024-02-29 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_Module', '0005_user_ticket_ticket_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_message',
            name='is_answered',
            field=models.BooleanField(default=False, verbose_name='آیا این پیام پاسخ دارد'),
        ),
    ]
