# Generated by Django 4.2 on 2024-03-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_Module', '0006_ticket_message_is_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_notifications',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='خوانده شده'),
        ),
    ]
