# Generated by Django 4.2 on 2024-03-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_Module', '0007_user_notifications_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='normal_user',
            name='admin_level',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=None, null=True),
        ),
        migrations.AddField(
            model_name='normal_user',
            name='user_type',
            field=models.CharField(choices=[('normal', 'عادی'), ('admin', 'ادمین')], default='عادی', max_length=10),
        ),
    ]
