# Generated by Django 4.2 on 2024-03-21 15:12

from django.db import migrations, models
import user_Module.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_Module', '0008_normal_user_admin_level_normal_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normal_user',
            name='admin_level',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3)], default=None, null=True, validators=[user_Module.models.admin_lvl_check]),
        ),
    ]
