# Generated by Django 4.2 on 2025-02-09 00:54

from django.db import migrations, models
import django.db.models.deletion
import product_module.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='article_picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='article_images', verbose_name='تصویر مقاله')),
            ],
            options={
                'verbose_name': 'تصویر مقاله',
                'verbose_name_plural': 'تصاویر مقالات',
            },
        ),
        migrations.CreateModel(
            name='brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='برند کالا')),
            ],
            options={
                'verbose_name': 'برند محصول',
                'verbose_name_plural': 'برندهای محصولات',
            },
        ),
        migrations.CreateModel(
            name='colors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, max_length=30, null=True, verbose_name='رنگ')),
                ('color_to_display', models.CharField(default='white', max_length=30, verbose_name='رنگ html')),
                ('assigned_to_all_products', models.BooleanField(default=False, verbose_name='به همه کالا ها نسبت داده شده')),
            ],
            options={
                'verbose_name': 'رنگ',
                'verbose_name_plural': 'رنگ ها',
            },
        ),
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='product_images')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصولات',
            },
        ),
        migrations.CreateModel(
            name='product_article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', max_length=2000, verbose_name='متن مقاله')),
            ],
            options={
                'verbose_name': 'مقاله کالا',
                'verbose_name_plural': 'مقالات کالا ها',
            },
        ),
        migrations.CreateModel(
            name='product_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, unique=True, verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی محصول',
                'verbose_name_plural': 'دسته بندی محصولات',
            },
        ),
        migrations.CreateModel(
            name='product_color_avalibity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_left', models.IntegerField(default=0, validators=[product_module.models.product_count_validator], verbose_name='amount left')),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='عنوان کالا')),
                ('price', models.IntegerField(default=0, verbose_name='قیمت کالا')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت محصول')),
                ('short_description', models.CharField(blank=True, max_length=100, null=True, verbose_name='خلاصه توضیحات')),
                ('main_description', models.TextField(blank=True, max_length=300, null=True, verbose_name='توضیحات اصلی')),
                ('url', models.SlugField(default='', max_length=300, verbose_name='slug_field')),
                ('has_color_instances', models.BooleanField(default=False, verbose_name='وجود رنگ های مختلف ازاین محصول')),
                ('rating', models.IntegerField(default=0, verbose_name='امتیاز کالا')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.brands', verbose_name='بند محصول')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.product_category', verbose_name='دسته بندی کالا')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
            },
        ),
        migrations.CreateModel(
            name='product_wish_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.products', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'علاقه مندی کالا',
                'verbose_name_plural': 'علاقه مندی های کالا ها',
            },
        ),
    ]
