# Generated by Django 4.2 on 2023-12-28 20:37

from django.db import migrations, models
import django.db.models.deletion
import product_module.models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_color_avalibity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_left', models.IntegerField(default=0, validators=[product_module.models.product_count_validator], verbose_name='amount left')),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_module.colors', verbose_name='product color')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.products', verbose_name='product')),
            ],
        ),
    ]
