# Generated by Django 5.1.6 on 2025-05-01 00:45

import django.db.models.deletion
import product_module.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='product_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=1, validators=[product_module.models.review_score_validator], verbose_name='امتیاز به کالا')),
                ('author', models.ForeignKey(error_messages={'null': 'این فیلد نمی تواند خالی باشد'}, on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to=settings.AUTH_USER_MODEL, verbose_name='کاربر امتیاز دهنده')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product_module.products', verbose_name='محصول')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('product', 'author'), name='product author uniquness', violation_error_message='این کاربر قبلا به این کالا امتیاز داده است')],
            },
        ),
    ]
