# Generated by Django 4.2 on 2023-12-30 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_colors_color_to_display'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='color',
        ),
    ]
