# Generated by Django 4.2 on 2024-01-27 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0007_colors_assigned_to_all_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', max_length=2000, verbose_name='articles text')),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.products', verbose_name='parent product')),
            ],
        ),
    ]
