# Generated by Django 4.2 on 2024-02-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0010_alter_article_picture_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='عنوان کالا'),
        ),
        migrations.AlterField(
            model_name='products',
            name='url',
            field=models.SlugField(default='', max_length=300, verbose_name='slug_field'),
        ),
    ]
