# Generated by Django 4.2 on 2024-02-07 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0011_alter_products_title_alter_products_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_wish_list',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.products', verbose_name='کالا'),
        ),
    ]
