# Generated by Django 4.2 on 2025-01-26 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_message', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(20)], verbose_name='پیام اعلان')),
                ('notif_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اعلان')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
            ],
            options={
                'verbose_name': 'اعلان کاربر',
                'verbose_name_plural': 'اعلانات کاربران',
                'db_table': 'user notifications',
            },
        ),
    ]
