# Generated by Django 4.2 on 2025-01-26 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_notifications',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='گیرنده اعلان'),
        ),
    ]
