# Generated by Django 4.2 on 2025-01-26 20:28

from django.db import migrations, models
import order_module.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='زمان سثبت سفارش')),
                ('is_paid', models.BooleanField(default=False, verbose_name='وضعیت پرداخت')),
                ('total_price', models.FloatField(blank=True, null=True, verbose_name='قیمت نهایی سفارش')),
                ('order_number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='order number')),
                ('status', models.CharField(choices=[('confirmed', 'تایید شده'), ('rejected', 'رد شده'), ('not confirmed', 'تایید نشده')], default=('not confirmed', 'تایید نشده'), max_length=100, verbose_name='وضعیت سفارش')),
            ],
            options={
                'verbose_name': 'سفارش کاربر',
                'verbose_name_plural': 'سفارش های کاربران',
            },
        ),
        migrations.CreateModel(
            name='order_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, max_length=90, validators=[order_module.models.detail_count_validator], verbose_name='تعداد')),
                ('total_price', models.IntegerField(default=0, verbose_name='قیمت نهایی')),
            ],
        ),
        migrations.CreateModel(
            name='reciver_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50, verbose_name='نام')),
                ('last_name', models.CharField(default='', max_length=50, verbose_name='نام خانوادگی')),
                ('phone', models.IntegerField(default=0, max_length=100, verbose_name='شماره تلفن')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='ایمیل')),
                ('address', models.CharField(default='', max_length=100, verbose_name='آدرس')),
                ('city', models.CharField(default='', max_length=60, verbose_name='شهر')),
                ('postal_code', models.IntegerField(default=0, max_length=10, verbose_name='کد پستی')),
            ],
        ),
    ]
