# Generated by Django 4.2 on 2023-12-28 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='titles',
        ),
    ]
