# Generated by Django 4.2 on 2025-02-09 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_module', '0001_initial'),
        ('order_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.colors', verbose_name='رنگ محصول'),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='parent_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order_module.order', verbose_name='والد'),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.products', verbose_name='محصول'),
        ),
        migrations.AddField(
            model_name='order',
            name='recive_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order_module.reciver_info', verbose_name='مشخصات گیرنده'),
        ),
    ]
