# Generated by Django 4.2 on 2023-12-29 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0002_product_color_avalibity'),
        ('order_module', '0002_delete_titles'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_module.colors', verbose_name='رنگ محصول'),
        ),
    ]
