# Generated by Django 4.2 on 2024-02-12 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0003_order_detail_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='recive_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order_module.reciver_info', verbose_name='مشخصات گیرنده'),
        ),
    ]
