# Generated by Django 4.2 on 2024-03-23 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_module', '0004_alter_order_recive_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='recive_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order_module.reciver_info', verbose_name='مشخصات گیرنده'),
        ),
    ]
