# Generated by Django 4.2 on 2025-02-09 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticket_module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='user_ticket',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط'),
        ),
        migrations.AddField(
            model_name='ticket_message',
            name='parent_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket_module.ticket_message', verbose_name='پیام والد'),
        ),
        migrations.AddField(
            model_name='ticket_message',
            name='parent_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_module.user_ticket', verbose_name='تیکت والد'),
        ),
    ]
