# Generated by Django 4.2 on 2025-02-09 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debts',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='user whom you owe money'),
        ),
    ]
